plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.lab3_20222079'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "com.example.lab3_20222079"
        minSdk 34
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures{
        viewBinding true
    }
}

dependencies {
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
    // Retrofit para peticiones HTTP
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'

    // Convertidor Gson para Retrofit (incluye @SerializedName)
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

    // Librería Gson
    implementation 'com.google.code.gson:gson:2.10.1'
}